export const PAKISTAN_CITIES = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Gujranwala",
  "Peshawar",
  "Multan",
  "Hyderabad",
  "Islamabad",
  "Quetta",
  "Sargodha",
  "Sialkot",
  "Bahawalpur",
  "Jhang",
  "Gujrat",
  "Sheikhupura",
  "Mardan",
  "Kasur",
  "Rahim Yar Khan",
  "Sahiwal",
  "Okara",
  "Wah Cantonment",
  "Dera Ghazi Khan",
  "Mingora",
  "Mirpur Khas",
  "Chiniot",
  "Nawabshah",
  "Kamoke",
  "Burewala",
  "Jhelum",
  "Sadiqabad",
  "Khanewal",
  "Hafizabad",
  "Kohat",
  "Jacobabad",
  "Shikarpur",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Bahawalnagar",
  "Muridke",
  "Pakpattan",
  "Abbottabad",
  "Tando Adam",
  "Jaranwala",
  "Khairpur",
  "Chishtian",
  "Daska",
  "Mandi Bahauddin",
  "Ahmadpur East",
];
